version: 2
jobs:
  publish_prod:
    environment:
      IMAGE_NAME: matthieubouamama/api_proxy_crypted
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image prod
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t $IMAGE_NAME:latest -f Dockerfile/Dockerfile-prod .54
            docker push $IMAGE_NAME:latest
  publish_dev:
    environment:
      IMAGE_NAME: matthieubouamama/api_proxy_crypted
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image dev
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t $IMAGE_NAME:dev -f Dockerfile/Dockerfile-dev .
            docker push $IMAGE_NAME:dev
  publish_tag:
    environment:
      IMAGE_NAME: matthieubouamama/api_proxy_crypted
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image tag
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t $IMAGE_NAME:dev -f Dockerfile/Dockerfile-dev .
            docker push $IMAGE_NAME:$CIRCLE_TAG
workflows:
  version: 2
  build-master:
    jobs:
      - publish_dev:
          context: api_proxy
          filters:
            branches:
              only: master
      - publish_prod:
          context: api_proxy
          filters:
            branches:
              only: master
      - publish_tag:
          context: api_proxy
          filters:
            tags:
              only: /.*/