version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
        auth:
          username: matthieubouamama
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          docker build -t matthieubouamama/api_proxy_crypted:latest .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push  matthieubouamama/api_proxy_crypted:latest