version: 2
jobs:
  publish_prod:
    environment:
      IMAGE_NAME: matthieubouamama/api_proxy_crypted
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image prod
          command: |
            docker build -t $IMAGE_NAME:latest -f Dockerfile/Dockerfile-prod .
            docker push $IMAGE_NAME:latest
  publish_dev:
    environment:
      IMAGE_NAME: matthieubouamama/api_proxy_crypted
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image dev
          command: |
            docker build -t $IMAGE_NAME:dev -f Dockerfile/Dockerfile-dev .
            docker push $IMAGE_NAME:dev
workflows:
  version: 2
  build-master:
    jobs:
      - publish_dev:
          context: api_proxy
          filters:
            branches:
              only: master
      - publish_prod:
          context: api_proxy
          filters:
            branches:
              only: master